# Generated by Django 3.0.8 on 2020-07-08 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigcomments',
            name='located_at',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='map.Big'),
        ),
        migrations.AlterField(
            model_name='middle',
            name='big_theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='middle', to='map.Big'),
        ),
        migrations.AlterField(
            model_name='middlecomments',
            name='located_at',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='map.Middle'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='middle_theme',
            field=models.ManyToManyField(blank=True, related_name='stock', to='map.Middle'),
        ),
        migrations.AlterField(
            model_name='stockcomments',
            name='located_at',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='map.Stock'),
        ),
    ]
