# Generated by Django 3.0.8 on 2020-07-08 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20200708_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='big',
            name='hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='middle',
            name='hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stock',
            name='hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='middle',
            name='big_theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='middles', to='map.Big'),
        ),
    ]
