# Generated by Django 3.0.8 on 2020-07-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20200708_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='big',
            name='forget',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='middle',
            name='forget',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stock',
            name='forget',
            field=models.BooleanField(default=False),
        ),
    ]
